---
# This playbook will set the necessary dns address then join an AD domain. 
- name: domain-joiner
  hosts: management_gui
  gather_facts: no
  vars_prompt:
  - name: admin_name
    prompt: "Provide the domain administrator account"
    private: no
  - name: admin_password
    prompt: Provide the password
    private: yes
  
  tasks:
  - name: Set domain controller dns address
    win_dns_client:
      adapter_names: "*"
      ipv4_addresses: "{{ name_server }}"

  - name: join the domain
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ hostname }}"
      domain_admin_user: "{{admin_name}}" 
      domain_admin_password: "{{admin_password}}"
      domain_ou_path: "{{ ou }}"
      state: domain
    register: domain_state
  
  - name: reboot after joining domain
    when: domain_state.reboot_required
    win_reboot:
      connect_timeout: 15
      post_reboot_delay: 15
      reboot_timeout: 200
      msg: "Server config in proecss: rebooting...."