---
# this playbook configures blueteam ubuntu networking
- name: ubuntu-networking
  hosts: ubuntu_server
  tasks:
  - name: set the hostname
    hostname:
      name: "{{hostname}}"
    become: yes
  
  - name: add host to hosts file
    lineinfile:
      path: /etc/hosts
      line: '127.0.1.1 {{hostname}}'
    become: yes

  - name: push over the networking script
    template:
      src: files/ubuntu/ifcfg-script.j2
      dest: '/etc/netplan/config-{{device}}.yaml'
      mode: 0644
      owner: root
      group: root
      force: yes
    become: yes

  - name: restart networking
    shell: "sleep 5 && sudo netplan apply && sleep 5 && reboot"
    become: yes
    async: 1
    poll: 0