---
- name: windows-software
  hosts: windows_workstation
  gather_facts: no 

  tasks:
    - name: install software with win chocolatey
      win_chocolatey:
        name: '{{ item }}'
        state: present
      loop:  
        - 7zip
        - googlechrome
        - vscode
        - putty
        - python3
        - git
        - notepadplusplus